package org.firstinspires.ftc.teamcode.variables.enums;

public enum ExtendArmStates {
    FORCE_FEED_BACK, MAX_POS, LOW_POS, WAITING_FOR_RESET_CONFIRMATION, RESETTING_ZERO_POS, ZERO_POS_RESET, MANUAL_MOVEMENT, MOVING_TO_PRESET, PRESET_REACHED, FLOATING
}
